name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        arch: [i686, x86_64]
        
    runs-on: windows-latest
    steps:
      - name: Checkout codeblocks_sfmirror
        uses: actions/checkout@v4
        with:
          repository: arnholm/codeblocks_sfmirror

      # Since 32-bit packages are not supported officially, we need to use the archives.
      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2
        if: matrix.arch == 'i686'
        with:
          update: true
          msystem: mingw32
          location: D:\
          install: >-
            mingw-w64-i686-toolchain
            libtool
            patch
            automake-wrapper
            autoconf-wrapper
            mingw-w64-i686-tinyxml
            mingw-w64-i686-drmingw
            base-devel
            zip
            wget
            git
            p7zip
            mingw-w64-i686-hunspell
            mingw-w64-i686-boost

      - name: Set up wxWidgets 3.2
        if: matrix.arch == 'i686'
        shell: msys2 {0}
        run: |
          wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-wxwidgets3.2-common-3.2.6-2-any.pkg.tar.zst
          wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-wxwidgets3.2-common-libs-3.2.6-2-any.pkg.tar.zst
          wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-wxwidgets3.2-common-3.2.6-2-any.pkg.tar.zst
          wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-wxwidgets3.2-msw-3.2.6-2-any.pkg.tar.zst
          wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-wxwidgets3.2-msw-libs-3.2.6-2-any.pkg.tar.zst
          wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-wxwidgets3.2-msw-cb_headers-3.2.6-2-any.pkg.tar.zst
          pacman -U --noconfirm *.pkg.tar.zst
            
      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2
        if: matrix.arch == 'x86_64'
        with:
          update: true
          msystem: MINGW64
          location: D:\
          install: >-
            mingw-w64-x86_64-toolchain
            libtool
            patch
            automake-wrapper
            autoconf-wrapper
            mingw-w64-x86_64-tinyxml
            mingw-w64-x86_64-drmingw
            mingw-w64-x86_64-wxwidgets3.2-common-libs
            mingw-w64-x86_64-wxwidgets3.2-common
            mingw-w64-x86_64-wxwidgets3.2-msw
            mingw-w64-x86_64-wxwidgets3.2-msw-libs
            mingw-w64-x86_64-wxwidgets3.2-msw-cb_headers
            base-devel
            zip
            p7zip
            git
            mingw-w64-x86_64-hunspell
            mingw-w64-x86_64-boost

      - name: Build CodeBlocks
        id: build
        shell: msys2 {0}
        run: |
          ## Obtain revision number
          TAG=r$(git log --graph | grep 'git-svn-id' | head -n 1 | grep -o -e "@\([0-9]*\)" | tr -d '@ ')
          WX_VERSION=$(wx-config --version-full)
          NAME="CodeBlocks svn "${TAG}" with wxWidgets "${WX_VERSION}" Build"

          ## Build CodeBlocks
          ./bootstrap
          ./configure --disable-pch --with-contrib-plugins=all,-Valgrind --prefix=/opt/codeblocks
          make -j$(nproc) install
          mv /opt/codeblocks/lib/codeblocks/bin/*.dll /opt/codeblocks/bin/
          #mv /opt/codeblocks/lib/*.dll /opt/codeblocks/bin/
          7zr a -mx9 -mqs=on -mmt=on /opt/codeblocks-${{ matrix.arch }}.7z /opt/codeblocks/*

          if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_NAME=${NAME}" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
          fi
          
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ steps.build.outputs.RELEASE_TAG }}
          name: ${{ steps.build.outputs.RELEASE_NAME }}
          artifacts: "D:/msys64/opt/codeblocks-${{ matrix.arch }}.7z"
          body: |
            This is ${{ steps.build.outputs.RELEASE_NAME }}. Please read the instructions first.
          token: ${{ secrets.GITHUB_TOKEN }}
